platform :ios, '16.0'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'Metamorphosis' do
  use_frameworks!
  
  pod 'DebugFrame', :inhibit_warnings => true
  pod 'SwiftLint', '0.48.0', :inhibit_warnings => true
  pod 'SwiftGen', '6.5.1', :inhibit_warnings => true
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
